# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1_marks', models.IntegerField(default=0)),
                ('ct2_marks', models.IntegerField(default=0)),
                ('ct3_marks', models.IntegerField(default=0)),
                ('ct4_marks', models.IntegerField(default=0)),
                ('ct5_marks', models.IntegerField(default=0)),
                ('ct6_marks', models.IntegerField(default=0)),
                ('assignment1_marks', models.IntegerField(default=0)),
                ('assignment2_marks', models.IntegerField(default=0)),
                ('assignment3_marks', models.IntegerField(default=0)),
                ('attendance_marks', models.IntegerField(default=0)),
                ('term_final_marks', models.IntegerField(default=0)),
                ('viva1_marks', models.IntegerField(default=0)),
                ('viva2_marks', models.IntegerField(default=0)),
                ('experiment_marks', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('final_out_of_hundred', models.IntegerField(default=0)),
                ('class_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Class_of_course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classes_enrolled_in',
            field=models.ManyToManyField(through='cms.Enrolment', to='cms.Class_of_course'),
        ),
    ]
