# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170501_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_nom',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone_nom',
            new_name='phone_num',
        ),
    ]
